Repository bellshade/bellshade-website, pull requests merged in 2021-10, with the labels that each got.

#28 Menambahkan Meta SEO dan Menggunakan :where() di CSS
  index.html
  src/css/style.css
Labels: enhancement

#31 update: logo navbar bellshade
  index.html
  public/nav-logo-light.jpg
Labels: enhancement, ui

#38 docs: add gh template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#46 docs: update feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#39 chore: increase dev experience
  .commitlintrc.json
  .eslintignore
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.json
  .stylelintrc.json
  main.js
  package-lock.json
  package.json
  src/css/style.css
Labels: enhancement

#50 fix: Memperbaiki navbar dan tagline
  index.html
Labels: bug

#44 Gantitooltip
  main.js
  src/css/tooltip.css
  src/js/appendMember.js
Labels: enhancement
