Repository bellshade/bellshade-website, pull requests merged in 2021-09, with the labels that each got.

#18 Performance and GitHub api
  .gitignore
  main.js
  src/css/style.css
  src/img/gif/backgroundGIF-min.gif
  src/js/appendMember.js
  src/js/constant.js
  src/js/githubApiWrapper.js
  tailwind.config.js
Labels: enhancement

#20 Bellshade api
  index.html
  main.js
  package.json
  src/css/style.css
  src/js/appendMember.js
  src/js/constant.js
  src/js/githubApiWrapper.js
  vite.config.js
Labels: enhancement, patch version

#23 Tailwind migration
  index.html
  package-lock.json
  package.json
  src/css/style.css
  src/js/appendMember.js
Labels: ui, epic
